# Generated by Django 3.0.7 on 2020-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(default='img/default_product_img.png', null=True, upload_to='static/img/post/', verbose_name='Изображение')),
                ('created_at', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
