# Generated by Django 3.0.7 on 2020-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='user_val',
            field=models.CharField(max_length=50),
        ),
    ]
