# Generated by Django 3.0.7 on 2020-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='img/default_product_img.png', null=True, upload_to='static/img/photo/', verbose_name='Изображение'),
        ),
    ]
