# Generated by Django 3.0.7 on 2020-06-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0002_auto_20200606_1718'),
        ('competitions', '0001_initial'),
        ('photos', '0002_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runners.Runner', verbose_name='Бегун'),
        ),
    ]
