# Generated by Django 3.0.7 on 2020-06-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200606_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
