# Generated by Django 3.0.7 on 2020-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(default='img/default_product_img.png', null=True, upload_to='static/img/competition/', verbose_name='Изображение')),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
